// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Attribute struct {
	Name         string  `json:"name"`
	Type         string  `json:"type"`
	DefaultValue string  `json:"defaultValue"`
	IsCore       string  `json:"isCore"`
	Description  *string `json:"description"`
	Example      *string `json:"example"`
}

type HasAttribute struct {
	Name       string       `json:"name"`
	Attributes []*Attribute `json:"attributes"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
